# Generated by Django 3.1 on 2020-08-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('act_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='timezone',
            field=models.CharField(default='UTC', max_length=32),
        ),
    ]
